name: Build site

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 22
        uses: actions/setup-node@v1
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build
        env:
          FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}
