name: Format

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Prettier
        run: npm install prettier

      - name: Format source
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Required
          commit_message: Auto-format code

          # Optional options appended to `git-commit`
          commit_options: "--no-verify --signoff"

          # Optional glob pattern of files which should be added to the commit
          file_pattern: src gatsby-*.js

          # Optional local file path to the repository
          repository: .

          # Optional options appended to `git-push`
          push_options: "--force"
